### ISSUE TITLE
AMP meet-up 2024-03-19

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#165]
- [x] quick review of https://arche-curation.acdh-dev.oeaw.ac.at/browser/detail/527914
- [x] duplicate display of page number: https://github.com/Auden-Musulin-Papers/amp-app/issues/167#issue-2191584730
- [x] how can author names be displayed if linked to ORCID, eg doc 0031: `<author ref="https://orcid.org/0000-0002-3997-5193"/>`
- [x] multiple `biblScope` elements within `bibl`: https://github.com/Auden-Musulin-Papers/amp-app/issues/166
- [x] direct link to AMP documents from within AMP documents vs indirect reference to literary-work entity (which is, however, not yet directly linked to AMP document) https://mattermost.acdh.oeaw.ac.at/acdh/pl/4h591dcitbfb5pyp3hotqtjo9c and https://mattermost.acdh.oeaw.ac.at/acdh/pl/8abdyx6y7jrkukczk54g4cbaxy, eg doc 0030 `working on a memoir of W.H. Auden´s years in Austria`
    - [ ] if directly linked (as in doc0031: https://auden-musulin-papers.github.io/amp-app-dev/amp-transcript__0031.html?tab=3&img=on), a slider (in same column as quote and comment) might enable/disable display of links
- [x] could mobile IIIF viewer be more static?
- [x] https://github.com/Auden-Musulin-Papers/amp-app/issues/164 and https://github.com/Auden-Musulin-Papers/amp-app/issues/164#issuecomment-1996887096
- [x] better solution for hierarchy of links in comment in https://auden-musulin-papers.github.io/amp-app-dev/amp-transcript__0030.html?tab=1r&nte=on&prs=on&plc=on&wrk=on&org=on&eve=on&del=on&udl=on&wsp=on&ucl=on&cho=on&qte=on&img=on
- [x] Link to Mediathek wrongly displayed as `Wikidata` link in doc 0060 -> https://github.com/Auden-Musulin-Papers/amp-app/issues/168
![image](https://github.com/Auden-Musulin-Papers/amp-app/assets/77000983/dc7ab6c3-756d-40ee-9405-b270cea24bb1)
- [x] RL 11 Apr: questions/tasks on @linxOD's part?

**Comment by timofruehwirth** [comment]
solution for 3rd point:
```
                              <author sameAs="#tfruehwirth"/>
                              <author sameAs="#smayer"/>
```
