### ISSUE TITLE
AMP meet-up 2024-03-26

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#174]
- [ ] ARCHE
    - [ ] check APA label in ARCHE: https://github.com/Auden-Musulin-Papers/amp-data/issues/160
    - [x] double display of language in ARCHE: https://github.com/Auden-Musulin-Papers/amp-data/issues/161
    - [x] suggested citation in ARCHE and on web app: https://github.com/Auden-Musulin-Papers/amp-data/issues/162, see Seta's comment: https://mattermost.acdh.oeaw.ac.at/acdh/pl/3m3os3oeitfnirafsgxh8y1qih
- [ ] web app
    - [x] `date` after `space`: https://github.com/Auden-Musulin-Papers/amp-app/issues/164, see my comment: https://mattermost.acdh.oeaw.ac.at/acdh/pl/qhrgn6orbjnb5n61wae5ge7c1h
    - [x] external links related to literary-work entities (earlier "Wikidata", now nothing): #168 
    - [x] rename `Wikidata` section in organization entities: #170 
    - [x] `opener` only optional after `div type="letter_message"`: #169 
    - [x] search part of strings: #171 
    - [x] update DOI banner start page: #172 
    - [x] update X logo: #173 
- [x] RL activities?
- [ ] suggestions for analytical tools, visualizations
    - [ ] suggestion timeline (including events from XMLs)
