### ISSUE TITLE
please add relevant sections to release note v1 data/meta/release_note_v1-0-0.md

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#235]
- [x] technical information re search function (anything new?) and analytics (reference to Stefan Resch ...)
- [x] Feature Update Summary?
- [ ] Bug Fixes?
- [x] is what we have written in 1.1 correct?
- [x] any disclaimer necessary?

**Comment by linxOD** [comment]
in 1.1 we could add that there are currently three odd schemas:
* schema.odd = correspondence documents + photos
* schmema-prose.odd = prose documents
* schema-indexes.odd = index documents

Bugs:
* there haven't been any bugs from the last version that needed fixing as far as I know

Disclaimer:
* Basically we have the Impressum
* In regard to functionallity we could add that we do not garantee any functionallity or provide bugfixes in the future
* In regard to the content and quality or completness maybe but this would be a questions for the legal department

Analytics:
* we could add a reference to the network libarary from Stefan: https://github.com/acdh-oeaw/network-visualisation
* the diagram was created with Highcharts: https://www.highcharts.com

Search:
* no changes here except that facets are now in drop down menus

Feature summary:
*  instead of a update summary we might add a general summary of all feature since we release the first major version and not a pre-release?

**Comment by timofruehwirth** [comment]
- accessibility checks, html5 structure checks (for screen readers)
- frontend representation of changed TEI data
