### ISSUE TITLE
final to-do for v0.3 pre-release

### ISSUE THREAD

**Issue by timofruehwirth** [Auden-Musulin-Papers/amp-app#56]
please

- [x] update FWF logo on web app (see https://www.fwf.ac.at/fileadmin/files/Images/News_Presse/Presse/Logo/Logo-D/FWF_Logo_Zusatz_Dunkelblau_RGB_DE.png)
- [x] XSLT-enable italics for documentation (editorial-declaration.xml)
- [x] feature tiles on landing page should correspond to links of 'Papers' tab (`Auden Musulin Papers 1959-1973`, `Musulin as Memoirist 1976-1995`, `Photos`, `Auden through Computer Vision` PLUS `Explore ...`); replace photos in current tiles with suitable icons
- [x] please review the disclaimer we've added to the md draft of release note 0.3 and documentation regarding limitations to facsimile view in mobile version (btw we noticed that the facsimile window-size adjustment in the mobile version does not work - this might be an improvement for 0.4 or 0.5)
